# This docker-compose.yml is used for development. At is overwritten
# in part in production with `docker-compose.production.yml`
version: '2.3'

services:

  lab:
    runtime: nvidia

    ports:
      - 8787:8787

    environment:
      # Secure student access with a token.
      # See entrypoint.sh for how this is used.
      - JUPYTER_TOKEN

    volumes:
      # The s3_data_loader service will download data entities described in
      # /task/data_sources to the shared volume `data` which is made available
      # to students in `/dli/task/data` here via the shared `data` volume.
      - ./task/data:/dli/task/data

  nginx:
    image: nginx:1.15.12-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  s3_data_loader:
    image: 224292665285.dkr.ecr.us-east-1.amazonaws.com/s3_data_loader:latest
    volumes:
      # Mount `data_sources` into `/var/data_sources` so the container knows what to download.
      - ./task/data_sources:/var/data_sources

      # Mount the shared `./task/data` volume into `/data` where this container will download the data,
      # and where the content container will be able to read it.
      - ./task/data:/data
